### ISSUE TITLE
Includes missing (uint32_t, size_t)

### ISSUE THREAD

**Issue by sam1013** [seL4/refos#2]
Hey!

Got minor compilation errors due to missing includes for `uint32_t` and `size_t`.
I added `stdint.h` and `stddef.h`, see diff below. 

Host platform: x86_64 with Ubuntu 15.04
Target platform: ia32
Compiler: gcc (Ubuntu 4.9.2-10ubuntu13) 4.9.2
Configuration: `ia32_debug_test_defconfig`

PS: Cool work! Just played a round of tetris :)

Regards, 
Sammey

--- Git diff begins here ---

diff --git a/impl/libs/librefos/include/refos/refos.h b/impl/libs/librefos/include/refos/refos.h
index 6eea0df..f09abe2 100644
--- a/impl/libs/librefos/include/refos/refos.h
+++ b/impl/libs/librefos/include/refos/refos.h
@@ -11,6 +11,7 @@
 #ifndef _REFOS_H_
 #define _REFOS_H_

+#include <stdint.h>
 #include <sel4/sel4.h>
 #include <refos/error.h>

diff --git a/impl/libs/librefos/include/refos/share.h b/impl/libs/librefos/include/refos/share.h
index 60fd8e5..86ef759 100644
--- a/impl/libs/librefos/include/refos/share.h
+++ b/impl/libs/librefos/include/refos/share.h
@@ -21,6 +21,7 @@
 #ifndef _REFOS_SHARE_H_
 #define _REFOS_SHARE_H_

+#include <stddef.h>
 #include "refos.h"

 /*! @brief Read from a shared buffer.

**Comment by hypernewbie** [comment]
Mind creating a pull request?

Thanks for fixing this. Have you tried the nethack? :)
